permalink: /:title
highlighter: rouge
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,ldquo,rdquo
  auto_ids: false
name: Ross Penman
url: "https://rosspenman.com"
include: [".well-known"]
sass:
  sass_dir: _sass
